name: Building

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login  
      run: docker login -u naomisoubhia -p  dckr_pat_sDIsdmXfBmRFRB5wC99VINvWGCs
    - name: build image
      run: docker build -t naomisoubhia/checkpoint1 .
    - name: push to docker
      run: docker push naomisoubhia/checkpoint1
