# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rm87272-checkpoint1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f0ee6b70eaaf4253b6f793a5136c695e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_009ec71e51d2415a816fd21cc1dfc246 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f0ee6b70eaaf4253b6f793a5136c695e }}/checkpoint1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rm87272-checkpoint1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dc3a7345c7a8467ca9a1229238a3b0ed }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f0ee6b70eaaf4253b6f793a5136c695e }}/checkpoint1:${{ github.sha }}'